### PR TITLE
fix(_index.js, method.js) id not working with html, wrapperhtml not w… issues #59 , #58

### LINKED ISSUE #58: wrapperClass is missing
Just found out the `wrapperClass` option was missing after version 4 while it is still available from [v3.1.0](https://github.com/viivue/easy-select/blob/v3.1.0/README.md).

```[tasklist]
### Tasks
- [ ] Add `wrapperClass` option, check v3.1.0 for correct implementation.
```

### LINKED ISSUE #59: Set ID via HTML init does not work
Screenshot 2025-01-10 at 15 24 49

### PR DESCRIPTION
**Pull request by Thanhdan0811**
Fix 2 issues : #59 , #58 

issues 59 : change code in _index.js.
issues 58 : change code in methods.js.

### CODE REVIEW

File: src/_index.js [hunk 1]
```diff
@@ -25,15 +25,24 @@ class EasySelect{
...
             attributeName: ATTRS.init,
-            defaultOptions: {...DEFAULTS, ...options, id: this.id},
-            numericValues: ['autoShow']
+            defaultOptions: {...DEFAULTS, ...options, id: null},
+            numericValues: ['autoShow'],
+            onIsString: value => {
+                if(!this.id) {
+                    this.id = value;
+                }
+                console.log(value); // => "hello-world"
```
Comment (phucbm) [inline src/_index.js]: Please remove all testing console log.

File: src/_index.js [hunk 2]
```diff
@@ -25,15 +25,24 @@ class EasySelect{
         });
 
         // get options and assign ID
-        this.id = options.id || this.selectTag.id || DEFAULTS.id;
+        // this.id = options.id || this.selectTag.id;
```
Comment (phucbm) [inline src/_index.js]: You can remove this line and the related comment.

File: src/_index.js [hunk 3]
```diff
@@ -25,15 +25,24 @@ class EasySelect{
...
+            numericValues: ['autoShow'],
+            onIsString: value => {
+                if(!this.id) {
+                    this.id = value;
+                }
+                console.log(value); // => "hello-world"
+            }
         });
 
+        this.options.id = options.id || this.selectTag.id || this.options.id || this.id || DEFAULTS.id;
```
Comment (phucbm) [inline src/_index.js:48]: Please put a comment to describe this line.

File: src/methods.js [hunk 4]
```diff
@@ -90,6 +90,11 @@ export function create(context){
     // add current HTML
     context.wrapper.insertAdjacentHTML('beforeend', getCurrentHTML(context));
 
+    // add wrapperClass option
```
Comment (phucbm) [inline src/methods.js:93]: `context.options.wrapperClass?.trim()` is duplicated.

**Review by phucbm — CHANGES_REQUESTED** [review]
Please check my comments.

**Review by phucbm — APPROVED** [review]
